SELECT
     DMFASRPT.LOAN_TRANCHES.DEBT_CATEGORY,
     DMFASRPT.LOAN_TRANCHES.DEBT_SOURCE,
     DMFASRPT.LOAN_TRANCHES.CREDITOR_NAME,
     DMFASRPT.TRA_ANOMALIES.LO_NO,
     DMFASRPT.TRA_ANOMALIES.TRA_NO,
     DMFASRPT.CD_NMS.NAME,
     DMFASRPT.MSG_TXTS.TEXT
FROM
     DMFASRPT.TRA_ANOMALIES INNER JOIN DMFASRPT.LOAN_TRANCHES ON DMFASRPT.TRA_ANOMALIES.LO_NO = DMFASRPT.LOAN_TRANCHES.LOAN_ID
     AND DMFASRPT.TRA_ANOMALIES.TRA_NO = DMFASRPT.LOAN_TRANCHES.TRANCHE_NO
     INNER JOIN DMFASRPT.AM_ANOMALIES ON DMFASRPT.TRA_ANOMALIES.AA_NO = DMFASRPT.AM_ANOMALIES.AA_NO
     INNER JOIN DMFASRPT.CD_NMS ON DMFASRPT.AM_ANOMALIES.CD_GRAVITY_LEVEL = DMFASRPT.CD_NMS.CD_CODE
     AND DMFASRPT.CD_NMS.CG_NO = DMFASRPT.AM_ANOMALIES.CG_GRAVITY_LEVEL
     INNER JOIN DMFASRPT.MSG_TXTS ON DMFASRPT.AM_ANOMALIES.ME_NO = DMFASRPT.MSG_TXTS.ME_NO
     AND DMFASRPT.MSG_TXTS.LA_ID = DMFASRPT.CD_NMS.LA_ID
WHERE
     DMFASRPT.CD_NMS.LA_ID = 1
 AND ((DMFASRPT.TRA_ANOMALIES.AA_NO = DMFASRPT.AM_ANOMALIES.AA_NO)
 AND (DMFASRPT.CD_NMS.LA_ID = DMFASRPT.MSG_TXTS.LA_ID)
 AND (DMFASRPT.AM_ANOMALIES.ME_NO = DMFASRPT.MSG_txts.ME_NO)
 AND (DMFASRPT.AM_ANOMALIES.CD_GRAVITY_LEVEL = DMFASRPT.CD_NMS.CD_CODE)
 AND (DMFASRPT.AM_ANOMALIES.CG_GRAVITY_LEVEL = DMFASRPT.CD_NMS.CG_NO)
 AND (DMFASRPT.TRA_ANOMALIES.LO_NO = DMFASRPT.LOAN_TRANCHES.LOAN_ID)
 AND (DMFASRPT.TRA_ANOMALIES.TRA_NO = DMFASRPT.LOAN_TRANCHES.TRANCHE_NO))
 AND DMFASRPT.LOAN_TRANCHES.DEBT_SOURCE = 'EXTERNAL'
ORDER BY
     DMFASRPT.LOAN_TRANCHES.DEBT_CATEGORY ASC,
     DMFASRPT.LOAN_TRANCHES.DEBT_SOURCE ASC,
     DMFASRPT.LOAN_TRANCHES.CREDITOR_NAME ASC,
     DMFASRPT.TRA_ANOMALIES.LO_NO ASC,
     DMFASRPT.TRA_ANOMALIES.TRA_NO ASC
