-- Guaranteed kreditlər
SELECT
    'GUARANTEED' AS GUARANTEE_TYPE,
    COUNT(*) AS NUM_CREDITS,
    ROUND(AVG(DSO.D_CRED_VAL - DSO.D_SCH)) AS AVG_DELAY_DAYS,
    SUM(DSO.AMT_CU_USD) AS TOTAL_DELAYED_AMOUNT
FROM 
    DMFASRPT.DEBT_SERV_OPERS DSO
JOIN 
    LOAN_TRANCHES LT ON DSO.LO_NO = LT.LOAN_ID AND DSO.TRA_NO = LT.TRANCHE_NO
WHERE 
    LT.PUBLIC_GUARANTEE = 'GUARANTEED'
    AND DSO.D_CRED_VAL > DSO.D_SCH + 30
    AND LT.STATUS = 'ACTIVE'
     AND DSO.D_SCH > '01-JAN-2024'
GROUP BY 
    LT.PUBLIC_GUARANTEE

UNION ALL

-- Non-Guaranteed kreditlər
SELECT
    'NON-GUARANTEED' AS GUARANTEE_TYPE,
    COUNT(*) AS NUM_CREDITS,
    ROUND(AVG(DSO.D_CRED_VAL - DSO.D_SCH)) AS AVG_DELAY_DAYS,
    SUM(DSO.AMT_CU_USD) AS TOTAL_DELAYED_AMOUNT
FROM 
    DMFASRPT.DEBT_SERV_OPERS DSO
JOIN 
    LOAN_TRANCHES LT ON DSO.LO_NO = LT.LOAN_ID AND DSO.TRA_NO = LT.TRANCHE_NO
WHERE 
    LT.PUBLIC_GUARANTEE = 'NON-GUARANTEED'
    AND DSO.D_CRED_VAL > DSO.D_SCH + 30
    AND LT.STATUS = 'ACTIVE'
       AND DSO.D_SCH > '01-JAN-2024'
GROUP BY 
    LT.PUBLIC_GUARANTEE;
