SELECT
     LOAN_TRANCHES.TRANCHE_NO,
     LOAN_TRANCHES.DEBT_CATEGORY,
     LOAN_TRANCHES.LOAN_ID,
     LOAN_TRANCHES.CREDITOR_NAME,
     LOAN_TRANCHES.DEBTOR_NAME,
     DMFASRPT.CD_NMS.NAME,
     CD_NMS_A.NAME AS NAME_A,
     DMFASRPT.SCH_DEBT_SERV_PMTS.AMT,
     DMFASRPT.SCH_DEBT_SERV_PMTS.AMT_UNPAID,
     DMFASRPT.SCH_DEBT_SERV_PMTS.D_PMT_SCH,
     DMFASRPT.SCH_DEBT_SERV_PMTS.AMT_ORDERED_UNPAID,
     DMFASRPT.SCH_DEBT_SERV_PMTS.SDSP_IDP,
     DMFASRPT.SCH_DEBT_SERV_PMTS.D_SCH,
     LOAN_TRANCHES.PUBLIC_GUARANTEE,
     LOAN_TRANCHES.TRANCHE_CURRENCY,
     LOAN_TRANCHES.INTEREST_RATE_TYPE
FROM
     DMFASRPT.SCH_DEBT_SERV_PMTS INNER JOIN LOAN_TRANCHES LOAN_TRANCHES ON DMFASRPT.SCH_DEBT_SERV_PMTS.LO_NO = LOAN_TRANCHES.LOAN_ID
     AND DMFASRPT.SCH_DEBT_SERV_PMTS.TRA_NO = LOAN_TRANCHES.TRANCHE_NO
     INNER JOIN DMFASRPT.CD_NMS ON DMFASRPT.SCH_DEBT_SERV_PMTS.CD_TRNS_TYP = DMFASRPT.CD_NMS.CD_CODE
     AND DMFASRPT.SCH_DEBT_SERV_PMTS.CG_TRNS_TYP = DMFASRPT.CD_NMS.CG_NO
     INNER JOIN DMFASRPT.CD_NMS CD_NMS_A ON DMFASRPT.SCH_DEBT_SERV_PMTS.CG_SCH_PMT_STAT = CD_NMS_A.CG_NO
     AND DMFASRPT.SCH_DEBT_SERV_PMTS.CD_SCH_PMT_STAT = CD_NMS_A.CD_CODE
WHERE
     LOAN_TRANCHES.DURATION IN ('MEDIUM/LONG-TERM','SHORT-TERM')
 AND DMFASRPT.CD_NMS.LA_ID = '1'
 AND CD_NMS_A.LA_ID = '1'
 AND LOAN_TRANCHES.DEBT_SOURCE = 'EXTERNAL'
 AND LOAN_TRANCHES.STATUS = 'ACTIVE'
 AND DMFASRPT.SCH_DEBT_SERV_PMTS.D_SCH BETWEEN trunc(sysdate,'MM')and LAST_DAY(SYSDATE)
ORDER BY
     DMFASRPT.SCH_DEBT_SERV_PMTS.D_SCH ASC,
     LOAN_TRANCHES.CREDITOR_NAME ASC
